// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateMakefile(arg1) {
  return window['go']['backend']['App']['GenerateMakefile'](arg1);
}
