// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateMakefile(arg1:Array<backend.MakefileEntry>):Promise<string>;
